const APP_ACTIONS = {
    TOGGLE: 'TOGGLE',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_USER_RETURNED_MESSAGE: 'SET_USER_RETURNED_MESSAGE',
    SET_IS_PASSWORD: 'SET_IS_PASSWORD',
    SET_IS_USER_lOGGED : 'SET_IS_USER_LOGGED'
  };

const USER_ACTIONS = {
  SET_PROFILE_PICTURE : 'SET_PROFILE_PICTURE',
  RESET_PASSWORD : 'RESET_PASSORD',
  SET_USER_PROFLE_INFORMATION : 'SET_USER_PROFILE_INFORMATION',
  UPDATE_USER_INFORMATION : 'UPDATE_USER_INFORMATION'
}

const PASSWORD_VISIBILITY = {
  IS_PASSWORD_VISIBLE : 'SET_PASSWORD_VISIBLE',
  IS_CONFIRM_PASSWORD_VISIBLE : 'SET_CONFIRM_PASSWORD_VISIBLE'
}


const ACTIONS = {
  APP_ACTIONS,
  USER_ACTIONS,
  PASSWORD_VISIBILITY,
}


export {ACTIONS};