const APP_ACTIONS = {
    TOGGLE: 'TOGGLE',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_USER_RETURNED_MESSAGE: 'SET_USER_RETURNED_MESSAGE',
    SET_IS_PASSWORD: 'SET_IS_PASSWORD',
  };

const USER_ACTIONS = {
  SET_PROFILE_PICTURE : 'SET_PROFILE_PICTURE',
  RESET_PASSWORD : 'RESET_PASSORD'
}

const PASSWORD_VISIBILITY = {
  IS_PASSWORD_VISIBLE : 'SET_PASSWORD_VISIBLE',
  IS_CONFIRM_PASSWORD_VISIBLE : 'SET_CONFIRM_PASSWORD_VISIBLE'
}


const ACTIONS = {
  APP_ACTIONS,
  USER_ACTIONS,
  PASSWORD_VISIBILITY,
}


export {ACTIONS};