const APP_ACTIONS = {
    TOGGLE: 'TOGGLE',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_USER_RETURNED_MESSAGE: 'SET_USER_RETURNED_MESSAGE',
    SET_IS_PASSWORD: 'SET_IS_PASSWORD',
  };

const USER_ACTIONS = {
  SET_PROFILE_PICTURE : 'SET_PROFILE_PICTURE',
  RESET_PASSWORD : 'RESET_PASSORD'
}


const ACTIONS = {
  APP_ACTIONS,
  USER_ACTIONS,
}


export {ACTIONS};